---

# ansible-playbook --inventory inventory.ini setup_server.yaml

- name: install streamlit
  hosts: target
  tasks:
    
    - name: apt install python3-venv
      become: true
      apt:
        name: python3-venv
        state: present

    - name: pip install streamlit plotly
      pip:
        virtualenv_command: python3 -m venv
        virtualenv: "{{ venv_environment }}"
        name: 
          - streamlit
          - plotly

- name: ufw
  hosts: target
  become: true
  tasks:
    - name: enable
      ufw:
        state: enabled
    - name: 8501
      ufw:
        port: 8501
        rule: allow
    - name: OpenSSH
      ufw:
        name: OpenSSH
        rule: allow

- name: systemd streamlit hello
  hosts: target
  become: true
  tasks:

    - name: streamlit-hello.sh
      become: false
      copy:
        dest: "{{ streamlit_start_script }}"
        mode: 0755
        content: |
          #!/bin/bash

          . {{ venv_environment }}/bin/activate

          # streamlit hello

          streamlit hello \
                  --server.address 127.0.0.1 \
                  --server.port 8501 \
                  --server.enableCORS false

    - name: /etc/systemd/system/streamlit-hello.service
      copy:
        dest: /etc/systemd/system/streamlit-hello.service
        content: |
          [Unit]
          Description=streamlit hello
          
          [Service]
          ExecStart={{ streamlit_start_script }}
          
          [Install]
          WantedBy=multi-user.target

    - name: systemctl daemon-reload
      command: systemctl daemon-reload

    - name: Enable streamlit-hello
      systemd:
        name: streamlit-hello
        enabled: true

    - name: Start streamlit-hello
      systemd:
        name: streamlit-hello
        state: started          

- name: apache
  vars:
    http_port: "80"
    disable_default: true    
  hosts: target
  become: true
  tags: apache
  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: apt apache2
      become: true
      apt:
        name: apache2
        state: present
    
    - name: modules
      apache2_module:
        state: present
        name: "{{ item }}"
      loop:
        - proxy
        - proxy_http
        - proxy_balancer
        - lbmethod_byrequests
        - rewrite

    - name: Create document root
      file:
        path: "/var/www/{{ fqdn }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
    
    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/{{ fqdn }}/index.html"

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ fqdn }}.conf"

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ fqdn }}.conf
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: ufw
      ufw:
        name: Apache Full
        rule: allow

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
          
- name: let's encrypt

  hosts: target
  tags: letsencrypt
  tasks:

    - name: apt update
      become: true
      apt:
        update_cache: yes

    - name: apt
      become: true
      apt:
        name:
          - certbot
          - python3-certbot-apache
        state: present

    - name: Obtain and configure SSL certificate using Certbot
      become: true
      shell: >
        certbot --apache --agree-tos --email {{ email }} --non-interactive --domains {{ fqdn }}

- name: apache ssl config
  hosts: target
  become: true
  tasks:

    - name: ls-ssl.conf
      become: true
      copy:
        dest: /etc/apache2/sites-available/{{ fqdn }}-le-ssl.conf
        mode: 0644
        content: |
          <IfModule mod_ssl.c>
          <VirtualHost *:443>
              ServerAdmin webmaster@localhost
              ServerName {{ fqdn }}
              # ServerAlias www.{{ fqdn }}
              DocumentRoot /var/www/{{ fqdn }}
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined

              RewriteEngine On
              RewriteCond %{HTTP:Upgrade} =websocket [NC]
              RewriteRule /(.*)         ws://127.0.0.1:8501/$1 [P,L]

              RewriteCond %{HTTP:Upgrade} !=websocket [NC]
              RewriteRule /(.*)           http://127.0.0.1:8501/$1 [P,L]

              ProxyPass        / http://127.0.0.1:8501
              ProxyPassReverse / http://127.0.0.1:8501

              ProxyPass        / ws://127.0.0.1:8501
              ProxyPassReverse / ws://127.0.0.1:8501

              Include /etc/letsencrypt/options-ssl-apache.conf
              SSLCertificateFile    /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem
              SSLCertificateKeyFile /etc/letsencrypt/live/{{ fqdn }}/privkey.pem
          </VirtualHost>
          </IfModule>
          
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded




